[package]
name = "rust_embedded_nrf52"
version = "0.1.0"
edition = "2024"


[dependencies]
cortex-m-rt = "0.7.3"
defmt = "1"
defmt-rtt = "1"
embedded-storage = "0.3.1"
embedded-storage-async = "0.4.1"
heapless = "0.8.0"
atomic-pool = "1.0.1"
static_cell = "2.0.0"
embassy-sync = "0.6.0"


[dependencies.panic-probe]
version = "1"
features = [ "print-defmt" ]


[dependencies.futures]
version = "0.3.29"
default-features = false


[dependencies.embassy-executor]
version = "0.7.0"
features = [
"arch-cortex-m",
"executor-thread",
"executor-interrupt",
"defmt"
]


[dependencies.embassy-time]
version = "0.4.0"
features = [ "defmt", "defmt-timestamp-uptime" ]


[dependencies.embassy-nrf]
version = "0.3.0"
features = [ "defmt", "gpiote", "time-driver-rtc1", "nrf52840" ]


[dependencies.nrf-softdevice]
version = "0.1.0"
git = "https://github.com/embassy-rs/nrf-softdevice.git"
features = [
"defmt",
"ble-peripheral",
"ble-central",
"critical-section-impl",
"nrf52840",
"s140",
"ble-l2cap",
"ble-gatt-server",
"ble-gatt-client",
"ble-sec"
]


[dependencies.nrf-softdevice-s140]
version = "0.1.1"
